name: Build and Test

on:
  push:
    branches:
      - main
      - feature/**
      - fix/**
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm ci
      - run: |
          npm run build
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test Results All
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          comment-title: Test Results All
          results-path: ./files/ab/*.trx
          allow-failed-tests: true

      - uses: actions/checkout@v3
      - name: Test Results All Show Output
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          comment-title: Test Results All
          results-path: ./files/ab/*.trx
          allow-failed-tests: true
          show-test-output: true
     